export enum Ingredients {
    strIngredient1  = "strIngredient1",
    strIngredient2  = "strIngredient2",
    strIngredient3  = "strIngredient3",
    strIngredient4  = "strIngredient4",
    strIngredient5  = "strIngredient5",
    strIngredient6  = "strIngredient6",
    strIngredient7  = "strIngredient7",
    strIngredient8  = "strIngredient8",
    strIngredient9  = "strIngredient9",
    strIngredient10 = "strIngredient10",
    strIngredient11 = "strIngredient11",
    strIngredient12 = "strIngredient12",
    strIngredient13 = "strIngredient13",
    strIngredient14 = "strIngredient14",
    strIngredient15 = "strIngredient15",
    strIngredient16 = "strIngredient16",
    strIngredient17 = "strIngredient17",
    strIngredient18 = "strIngredient18",
    strIngredient19 = "strIngredient19",
    strIngredient20 = "strIngredient20",
}